### ISSUE TITLE
SW_ACP_PATH not set, unable to start mf_connector/class browser

### ISSUE THREAD

**Issue by StevenLooman** [roadrunner1776/magik#3]
In version `magik-mode-20200217.1213` the environment variable `SW_ACP_PATH` is not set within the emacs environment when selecting the Smallworld Core Product Installation. As a result, the `mf_connector` cannot be located and started when starting the class browser. Using Smallworld 5.

In version `magik-mode-20181005.841` (haven't checked other versions) the environment is initialized from function `magik-version-set-environment` by calling `${SMALLWORLD_GIS}/config/environment.bat`, this functionality is no longer present in version `magik-mode-20200217.1213`.

A possible fix/workaround would be to set the `SW_ACP_PATH` environment variable from `magik-version-set-environment`, such as:
```
(defun magik-version-set-environment (smallworld-gis stream version)
  "Modify the process and exec-path environment given stream and smallworld-gis path."
  (setenv "SMALLWORLD_GIS" smallworld-gis)
  (setenv "SW_ACP_PATH" (expand-file-name "etc/x86" smallworld-gis))
  (setenv "SW_STREAM" stream)
  (setenv "SW_VERSION" version))
```

**Comment by StevenLooman** [comment]
Note that on Linux the sub-directory isn't `etc/x86`, but `etc/Linux.x86`.

**Comment by ReinhardHahn** [comment]
Hi Steven,

I suggest to close your issue as resolved, probably by 4th Mar 2020 with https://github.com/roadrunner1776/magik/commit/e54f934952cde3f96d6a131968295d993b3cf624. At least I cannot reproduce it with the current version.

Just as a hint for people using SW 4.x: To get the CB running you can either customize the magik-aliases-layered-products-file or copy you product\custom\LAYERED_PRODUCTS file to $SMALLWORLD_GIS/../smallworld_registry as usual from SW 5.x on..

**Comment by StevenLooman** [comment]
Thank you for your response. I'm closing the issue.

**Comment by ReinhardHahn** [comment]
For using classbrowser with GNU/Linux a solution is available with https://github.com/roadrunner1776/magik/pull/7
